// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0OBj0LmJI5pbWSGWY4hLkoAMHB3UW_Lk',
    appId: '1:1019671918439:web:ce4e2c1e5655683c38e1c2',
    messagingSenderId: '1019671918439',
    projectId: 'myhealthtracker-afd26',
    authDomain: 'myhealthtracker-afd26.firebaseapp.com',
    storageBucket: 'myhealthtracker-afd26.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVEhKuQ-FAqaj4I8HZP2P9nJI6q-UI-nk',
    appId: '1:1019671918439:android:0b54b7f40807c77a38e1c2',
    messagingSenderId: '1019671918439',
    projectId: 'myhealthtracker-afd26',
    storageBucket: 'myhealthtracker-afd26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2dApyxCCBprgs0vWotWy4yL0HWB-9zoI',
    appId: '1:1019671918439:ios:859f117c8f68ab0138e1c2',
    messagingSenderId: '1019671918439',
    projectId: 'myhealthtracker-afd26',
    storageBucket: 'myhealthtracker-afd26.firebasestorage.app',
    iosBundleId: 'com.example.myhealthTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2dApyxCCBprgs0vWotWy4yL0HWB-9zoI',
    appId: '1:1019671918439:ios:859f117c8f68ab0138e1c2',
    messagingSenderId: '1019671918439',
    projectId: 'myhealthtracker-afd26',
    storageBucket: 'myhealthtracker-afd26.firebasestorage.app',
    iosBundleId: 'com.example.myhealthTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0OBj0LmJI5pbWSGWY4hLkoAMHB3UW_Lk',
    appId: '1:1019671918439:web:d9049feb80f17a9e38e1c2',
    messagingSenderId: '1019671918439',
    projectId: 'myhealthtracker-afd26',
    authDomain: 'myhealthtracker-afd26.firebaseapp.com',
    storageBucket: 'myhealthtracker-afd26.firebasestorage.app',
  );
}
